### ISSUE TITLE
[SOLVED] HDA Not working in Houdini FX Version 18.5.351

### ISSUE THREAD

**Issue by dangerstudios** [sideeffects/HoudiniLiveLink#1]
[EDIT:] got it working, nothing to see here...

Hi, 

The buttons are not working on the ue4_livelink hda, it doesn't seem to be accessing the python code?

**Traceback (most recent call last):
  File "Sop/ue4_livelink/start_server", line 1, in <module>
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.351/houdini/python2.7libs\hou.py", line 47257, in __getattr__
    return _hou.HDAModule___getattr__(self, name)
AttributeError: 'module' object has no attribute 'start_server'**

[EDIT:] got it working, nothing to see here...

**Comment by dangerstudios** [comment]
Would it be possible to compile for the latest version of unreal?

4.24.**4**

At the moment it only supports; 4.24.**3**

**Comment by artofandresperez** [comment]
How did you get it to work

**Comment by stephenscollay** [comment]
For those lost souls who wash up on these shores. It's normally a sintax error in the python code with how the functions are laid out. Stray indentations, lack of a colon at the end of a function def etc. Have a look at the function definition after the one in the error.

**Comment by dangerstudios** [comment]
> How did you get it to work

I can't remember now sorry, but yeah probably a python syntax issue? let me know if you are still stuck and I can take a look.
